### ISSUE TITLE
Fix BTC/USD BTC/ILS ticker

### ISSUE THREAD

**Issue by shesek** [bitembassy/bitembassy.org#1]
It stopped working on the old website too.

**Comment by sha-265** [comment]
I think we should use the real bitcoin price: 1 BTC = 1 BTC.

**Comment by yoss1x** [comment]
Done :)

**Comment by sha-265** [comment]
Great :) I think you can close this issue: https://github.com/bitembassy/bitembassy.org/commit/3c83eef85bb2ef8a565e02b64faafb0650d0dcbe

**Comment by shesek** [comment]
Agreed. :)
